apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: configure-build
spec:
  description: >-
    App Studio Configure Build Secrets in Source. 
  results: 
    - name: registry-auth
      description: docker config location
    - name: buildah-auth-param
      description: pass this to the build optional params to conifigure secrets
  workspaces:
    - name: source
      optional: true
    - name: registry-auth
      optional: true
  steps:
    - name: appstudio-configure-build  
      image: appstudio-utils
      script: | 
        #!/usr/bin/env bash    
        echo "App Studio Configure Build" 

        AUTH=/workspace/registry-auth/.dockerconfigjson
        DEST=/workspace/source/.dockerconfigjson
        echo "Looking for Registry Auth Config: $AUTH"
        if [ -f "$AUTH" ]; then
          echo "$AUTH found" 
          echo

          cp $AUTH $DEST

          echo -n $DEST > /tekton/results/registry-auth  
          echo -n "--authfile $DEST"  >  /tekton/results/buildah-auth-param
          echo 
        else  
          echo "No $AUTH found." 
          echo -n " " > /tekton/results/registry-auth  
          echo -n " " > /tekton/results/buildah-auth-param
          echo 
        fi
