apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: configure-build-csi-secret
spec:
  description: >-
    App Studio Configure Build Secrets in Source.
  params:
    - name: shared-secret
  results:
    - name: registry-auth
      description: docker config location
    - name: buildah-auth-param
      description: pass this to the build optional params to conifigure secrets
  workspaces:
    - name: source
  volumes:
    - name: appstudio-push-secret
      csi:
        readOnly: true
        driver: csi.sharedresource.openshift.io
        volumeAttributes:
          sharedSecret: $(params.shared-secret)
  steps:
    - name: appstudio-configure-build
      image: registry.access.redhat.com/ubi8-minimal@sha256:574f201d7ed185a9932c91cef5d397f5298dff9df08bc2ebb266c6d1e6284cd1
      volumeMounts:
        - name: appstudio-push-secret
          mountPath: /workspace/registry-auth
      script: |
        #!/usr/bin/env bash
        echo "App Studio Configure Build"

        AUTH=/workspace/registry-auth/.dockerconfigjson
        DEST=/workspace/source/.dockerconfigjson
        echo "Looking for Registry Auth Config: $AUTH"
        if [ -f "$AUTH" ]; then
          echo "$AUTH found"
          echo

          cp $AUTH $DEST

          echo -n $DEST > /tekton/results/registry-auth
          echo -n "--authfile $DEST"  >  /tekton/results/buildah-auth-param
          echo
        else
          echo "No $AUTH found."
          echo -n " " > /tekton/results/registry-auth
          echo -n " " > /tekton/results/buildah-auth-param
          echo
        fi
