apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/displayName: cosign verify attestation
    tekton.dev/pipelines.minVersion: "0.19"
    tekton.dev/tags: cosign, chains, attestation
  labels:
    app.kubernetes.io/version: "0.1"
    operator.tekton.dev/provider-type: redhat
  name: cosign-verify-attestation
spec:
  description: cosign-verify-attestation verifies the attestation of the image reference with the provided public key.
  params:
  - description: Public key used to verify the signature. Provided as a PEM-encoded string or as a valid cosign key reference.
    name: PUBLIC_KEY
    type: string
  - description: Pull reference of the image to verify.
    name: IMAGE
    type: string
  results:
    - name: VERIFY_ATTESTATION_JSON
      description: Result of verification in JSON format
  steps:
  - script: |
      #!/usr/bin/env bash
      set -euo pipefail
      echo "App Studio Utility Task $(context.task.name)"
      [[ "$(workspaces.sslcertdir.bound)" == "true" ]] && export SSL_CERT_DIR="$(workspaces.sslcertdir.path)"
      /appstudio-utils/util-scripts/$(context.task.name).sh "$(params.IMAGE)" "$(params.PUBLIC_KEY)" "$(results.VERIFY_ATTESTATION_JSON.path)"
    name: verify
    image: appstudio-utils
  workspaces:
  - name: sslcertdir
    optional: true
