apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deprecated-image-check
spec:
  params:
    - name: IMAGE_REGISTRY
      description: "Image registry for the tested image"
      default: registry.access.redhat.com
    - name: IMAGE_REPOSITORY
      description: "Image repository name to test"
    - name: POLICY_DIR
      description: "Path to the directory containing conftest policies"
      default: "/project/repository/"
    - name: POLICY_NAMESPACE
      description: "Namespace for the conftest policy"
      default: "required_checks"

  results:
    - name: PYXIS_HTTP_CODE
      description: HTTP code returned by Pyxis API endpoint
    - description: Test output
      name: HACBS_TEST_OUTPUT

  steps:
    # Download Pyxis metadata about the image
    - name: query-pyxis
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        #!/usr/bin/env bash
        echo "Querying Pyxis for $(inputs.params.IMAGE_REPOSITORY)..."
        http_code=$(curl -s -o $(workspaces.sanity-ws.path)/repository_data.json -w '%{http_code}' "https://catalog.redhat.com/api/containers/v1/repositories/registry/$(inputs.params.IMAGE_REGISTRY)/repository/$(inputs.params.IMAGE_REPOSITORY)")

        echo "Response code: $http_code"
        echo -n $http_code > $(results.PYXIS_HTTP_CODE.path)

    # Run the tests and save output
    - name: run-conftest
      image: quay.io/redhat-appstudio/hacbs-test:stable
      script: |
        #!/usr/bin/env sh
        http_code=$(cat $(results.PYXIS_HTTP_CODE.path))

        if [ "$http_code" == "200" ];
        then
          echo "Running conftest using $(inputs.params.POLICY_DIR)"
          conftest test $(workspaces.sanity-ws.path)/repository_data.json -p $(inputs.params.POLICY_DIR) --no-fail \
          --namespace $(inputs.params.POLICY_NAMESPACE) -o json | tee $(workspaces.sanity-ws.path)/deprecated_image_check_output.json || echo "Some tests failed"
          echo "Done!"
          exit 0
        elif [ "$http_code" == "404" ];
        then
          echo "Image not found in Pyxis"
        else
          echo "Unexpected error (HTTP code $http_code) occured during running conftest"
        fi

    # Format the test results and save them as the Tekton result
    - name: test-format-result
      image: quay.io/redhat-appstudio/hacbs-test:stable
      script: |
        HACBS_ERROR_OUTPUT=$(jq -rc --arg date $(date +%s) --null-input \
          '{result: "ERROR", timestamp: $date}')
        HACBS_TEST_OUTPUT=$(jq -rce --arg date $(date +%s) \
          '.[] | { result: (if (.failures | length > 0) then "FAILURE" else "SUCCESS" end),
                   timestamp: $date,
                   namespace,
                   successes,
                   failures: (.failures // [])|map(.metadata.details.name)
                 }' $(workspaces.sanity-ws.path)/deprecated_image_check_output.json || true)
        echo "${HACBS_TEST_OUTPUT:-${HACBS_ERROR_OUTPUT}}" | tee $(results.HACBS_TEST_OUTPUT.path)
  workspaces:
    - name: sanity-ws
