apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hacbs-test-evaluation
spec:
  description: >-
    Show summary of HACBS tests
  workspaces:
    - name: workspace
  params:
    - name: BASE_IMAGE
  steps:
    - name: summary
      image: quay.io/redhat-appstudio/hacbs-test:latest
      workingDir: $(workspaces.workspace.path)/hacbs
      script: |
        #!/usr/bin/env bash

        # sanity-label-check required checks
        FAILURES=$(jq '.[] | .failures // {} | .[] | .msg' sanity-label-check-required_checks/sanity_label_check_output.json)
        if [ -n "$FAILURES" ]; then
          echo sanity-label-check-required_checks test FAIL:
          echo "$FAILURES"
        else
          echo sanity-label-check-required_checks test PASS
        fi
        echo -------------
        
        # sanity-label-check optional checks
        FAILURES=$(jq '.[] | .failures // {} | .[] | .msg' sanity-label-check-optional_checks/sanity_label_check_output.json)
        if [ -n "$FAILURES" ]; then
          echo sanity-label-check-optional_checks test FAIL:
          echo "$FAILURES"
        else
          echo sanity-label-check-optional_checks test PASS
        fi
        echo -------------

        # sanity-inspect-image
        if [ ! -s sanity-inspect-image/base_image_inspect.json ]; then
          echo sanity-inspect-image test FAIL
          echo Unable to inspect base image - $(params.BASE_IMAGE)
        else
           echo sanity-inspect-image test PASS
        fi
        echo -------------
