apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- buildah.yaml
- cleanup-build-directories.yaml
- configure-build.yaml
- git-clone.yaml
- init.yaml
- s2i-java.yaml
- s2i-nodejs.yaml
- sanity-label-check.yaml
- summary.yaml
- utils-task.yaml
- cosign-verify.yaml
- cosign-verify-attestation.yaml
- sanity-inspect-image.yaml
- hacbs-test-evaluation.yaml
- update-infra-deployments.yaml
- get-clair-scan.yaml
- conftest-clair.yaml
- verify-enterprise-contract.yaml
- sast-go.yaml
- sast-java-sec-check.yaml

patches:
  - path: patches/add-sbom-and-push.yaml
    target:
      group: tekton.dev
      version: v1beta1
      kind: Task
      labelSelector: build-definition.include = add-sbom-and-push
