---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sast-go
spec:
  workspaces:
    - name: workspace
  results:
    - description: Test output
      name: HACBS_TEST_OUTPUT
  steps:
    - name: sast-go
      image: quay.io/redhat-appstudio/hacbs-test:feature-sast
      workingDir: $(workspaces.workspace.path)/hacbs/$(context.task.name)
      script: |
        /usr/local/go/bin/gosec -no-fail -fmt=sarif -out=gosec_output.json $(workspaces.workspace.path)/... | tee gosec_output.txt
        GOSEC_EXIT_CODE=$?

        # Test if any package was found
        # Even with -no-fail, gosec uses exit code 1 for several states,
        # including when there are no packages found.
        grep "No packages found$" gosec_output.txt && echo "Exit 0 because no packages found" && exit 0
        exit $GOSEC_EXIT_CODE

    - name: test-format-result
      image: quay.io/redhat-appstudio/hacbs-test:feature-sast
      workingDir: $(workspaces.workspace.path)/hacbs/$(context.task.name)
      script: |
        HACBS_ERROR_OUTPUT=$(jq -rc --arg date $(date +%s) --null-input \
          '{result: "ERROR", timestamp: $date}')
        HACBS_TEST_OUTPUT=$(jq -rce --arg date $(date +%s) \
          '{ result: (if (.runs[].results | length > 0) then "FAILURE" else "SUCCESS" end),
                   timestamp: $date,
                   namespace: "default",
                   successes: 0,
                   failures: (.runs[].results // [])|map(.message.text)
                 }' gosec_output.json || true)
        echo "${HACBS_TEST_OUTPUT:-${HACBS_ERROR_OUTPUT}}" | tee $(results.HACBS_TEST_OUTPUT.path)
