apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: e2e-test
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/displayName: "E2E Tests"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task can be used to run e2e tests
  params:
    - name: e2e_test_namespace
      type: string
    - name: app_suffix
      type: string
    - name: ec_pipelines_repo_url
      type: string
    - name: ec_pipelines_repo_revision
      type: string
    - name: docker-build-bundle
      type: string
    - name: docker-build-oci-ta-bundle
      type: string
    - name: docker-build-multi-platform-oci-ta-bundle
      type: string
    - name: fbc-builder-bundle
      type: string
  steps:
    - name: e2e-test
      image: quay.io/redhat-user-workloads/konflux-qe-team-tenant/konflux-e2e/konflux-e2e-tests:9a6c4554c393b526a24c3b137a59faae436afc61
      command: ["/konflux-e2e/konflux-e2e.test"]
      # a la infra-deployment updates, when PRs merge in e2e-tests, PRs will be opened
      # against build-definitions to update this tag
      args: [
        "--ginkgo.label-filter=build-templates-e2e",
        "--ginkgo.no-color",
        "--ginkgo.v",
        "--ginkgo.timeout=2h"
      ]
      securityContext:
        capabilities:
          add:
          - SETFCAP
      env:
      - name: APP_SUFFIX
        value: "$(params.app_suffix)"
      - name: COMPONENT_REPO_URLS
        value: "https://github.com/konflux-qe-bd/devfile-sample-python-basic,https://github.com/konflux-qe-bd/retrodep,https://github.com/konflux-qe-bd/pip-e2e-test,https://github.com/konflux-qe-bd/fbc-sample-repo,https://github.com/konflux-qe-bd/docker-file-from-scratch"
      - name: QUAY_E2E_ORGANIZATION
        value: konflux-ci
      - name: E2E_APPLICATIONS_NAMESPACE
        value: "$(params.e2e_test_namespace)"
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: github
            key: token
      - name: QUAY_TOKEN
        valueFrom:
          secretKeyRef:
            name: quay-push-secret-konflux-ci
            key: .dockerconfigjson
      - name: MY_GITHUB_ORG
        value: konflux-qe-bd
      - name: EC_PIPELINES_REPO_URL
        value: $(params.ec_pipelines_repo_url)
      - name: EC_PIPELINES_REPO_REVISION
        value: $(params.ec_pipelines_repo_revision)
      - name: CUSTOM_DOCKER_BUILD_PIPELINE_BUNDLE
        value: "$(params.docker-build-bundle)"
      - name: CUSTOM_DOCKER_BUILD_OCI_TA_PIPELINE_BUNDLE
        value: "$(params.docker-build-oci-ta-bundle)"
      - name: CUSTOM_DOCKER_BUILD_OCI_MULTI_PLATFORM_TA_PIPELINE_BUNDLE
        value: "$(params.docker-build-multi-platform-oci-ta-bundle)"
      - name: CUSTOM_FBC_BUILDER_PIPELINE_BUNDLE
        value: "$(params.fbc-builder-bundle)"
