apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yaml-lint
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Code Quality
    tekton.dev/tags: linter
    tekton.dev/displayName: "YAML linter"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task can be used to perform lint check on YAML files
  workspaces:
    - name: shared-workspace
      description: A workspace that contains the fetched git repository.
  params:
    - name: args
      type: array
      description: extra args needs to append
      default: ["--help"]
  steps:
    - name: lint-yaml-files
      image: docker.io/cytopia/yamllint:1.26@sha256:1bf8270a671a2e5f2fea8ac2e80164d627e0c5fa083759862bbde80628f942b2  # tag: 1.23
      workingDir: $(workspaces.shared-workspace.path)
      command:
        - yamllint
      args:
        - $(params.args)
    - name: ensure-params-not-in-script
      image: quay.io/redhat-appstudio/appstudio-utils:d8a93bf5650424a4f20ee065578609792d70af1c
      script: |
        #!/bin/bash
        for task in $(find task -name '*.yaml'); do
          if yq '.spec.steps[] | .script' $task | grep -q 'params\.'; then
            FAILED_TASKS="$FAILED_TASKS $task"
          fi
        done
        if [ -n "$FAILED_TASKS" ]; then
          echo "Tasks contains params in script section (https://tekton.dev/docs/pipelines/tasks/#substituting-in-script-blocks)"
          echo $FAILED_TASKS | tr ' ' '\n' | sort
          exit 1
        fi
      workingDir: $(workspaces.shared-workspace.path)
