apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- analyze-devfile.yaml
- appstudio-configure-build.yaml
- appstudio-init.yaml
- appstudio-summary.yaml
- appstudio-tekton-bundle.yaml
- appstudio-utils.yaml
- cleanup-build-directories.yaml
- image-exists.yaml
