name: Validate PR - check task owners
'on':
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
jobs:
  check:
    name: Check Task OWNERS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check task owners
        run: |
          ./hack/check-task-owners.sh

      - name: Check renovate.json groups
        run: |
          #!/bin/bash
          set -euo pipefail

          renovate_content=$(cat renovate.json)
          ./hack/update_renovate_json_based_on_codeowners.py -o renovate.json

          uptodate=$(jq --argjson previous "$renovate_content" '$previous == .' renovate.json)
          echo "renovate.json is up to date: $uptodate"

          if [[ $uptodate == false ]]; then
              echo
              git --no-pager diff -- renovate.json
              echo
              echo "To apply the updates, run: ./hack/update_renovate_json_based_on_codeowners.py -o renovate.json"
              echo "Or run ./hack/generate-everything.sh to run all the generators at once."
              exit 1
          fi
